### PR TITLE
Update nix-language.md

### PR DESCRIPTION
**Pull request by drupol**
Fix markdown link

### CODE REVIEW

**Comment by drupol** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by fricklerhandwerk** [comment]
@drupol Thanks for the catch. Apparently I introduced more errors while fixing one. The intention was to use `[\`nix repl\`]` everywhere so one doesn't have to add the link reference separately. Would be lovely if you could fix that instead.

**Comment by drupol** [comment]
Hello,

I think I just fixed them all.

Let me know if it's ok.

**Comment by fricklerhandwerk** [comment]
Yes, thanks so much!

**Pull request merged**
