### PR TITLE
Move contributing from tutorials to top-level

### PR DESCRIPTION
**Pull request by yukiisbored**

### CODE REVIEW

**Comment by yukiisbored** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by zupo** [comment]
A requirement to merge this PR is a 301 Redirect from `https://nix.dev/tutorials/contributing` to `https://nix.dev/contributing` so that:
* people using existing links to `https://nix.dev/tutorials/contributing` don't get 404 and be discouraged
* keep the SEO juice

One option is to do the redirect with CloudFlare Pages / Netlify or whatever nix.dev is deployed with. 

The other option is to use https://github.com/sphinx-contrib/redirects.

**Comment by zupo** [comment]
`curl --head https://nix.dev` tells me `server: cloudflare`, so I'm assuming https://nix.dev is in fact deployed by Cloudflare Pages. 

I will now attempt to create a dummy temporary redirect using https://developers.cloudflare.com/pages/platform/redirects/ in a separate Pull Request. If it works, I'll do the same in this PR.

**Comment by zupo** [comment]
Redirects seems to work fine: https://github.com/NixOS/nix.dev/pull/360

**Review by zupo — APPROVED** [review]
Redirect added, looks good to merge to me now.

**Comment by brainrake** [comment]
Looks good, but I could not test locally.

**Pull request merged**
