### PR TITLE
remove flake.nix

### PR DESCRIPTION
**Pull request by fricklerhandwerk**
use niv for dependency management.

this follows our own tutorials on writing packages and development
shells, and we generally find it is easier to read and work with.

co-authored-by: @alejandrosame

### CODE REVIEW

**Review by infinisil — APPROVED** [review]
Looking good to me, just needs a rebase as far as I can see, or is there anything else needed?

**Comment by fricklerhandwerk** [comment]
I ran into morally unneeded rebuilds that led me to open https://github.com/nmattia/niv/pull/379. That kind of made me back off from the idea for a while. I'll give it another thought when my mind is fresh, rebasing it should be quick.

**Comment by RaitoBezarius** [comment]
@fricklerhandwerk As an alternative, https://github.com/andir/npins do exist too.

**Comment by infinisil** [comment]
I'd not worry about that, it's an orthogonal concern, let's not get stuck in too many rabbit holes. I'd be willing to merge this if rebased.

**Comment by infinisil** [comment]
It just occurred to me that we'd totally be breaking the automatic nixos.org updates [again](https://github.com/NixOS/nixos-homepage/pull/1142), since it [depends on `nix.dev`](https://github.com/NixOS/nixos-homepage/blob/2b75346c059648e4d060b17c479ea53fa85ab7af/flake.nix#L15) being a flake. I think that's okay though, nix.dev doesn't need to be a stable API surface.

**Review by infinisil — APPROVED** [review]

**Comment by infinisil** [comment]
This is needed for the homepage updates: https://github.com/NixOS/nix.dev/pull/792

**Comment by infinisil** [comment]
Opened https://github.com/NixOS/nixos-homepage/pull/1148

**Comment by wmertens** [comment]
I'm surprised that a PR that adds 150 LoC is considered simpler, and sad that but everyone is rallying behind flakes

**Pull request merged**
