### PR TITLE
Add prose lint checks with Vale

### PR DESCRIPTION
**Pull request by asymmetric**
Tons of errors, including false positives (e.g. "Eelco"). We might want to:

- Disable the spell-checker
- Add lots of exceptions
- Tell it to ignore capitalized words (but it still will complain about e.g. "npm")

For now, we use the default profile plus a rule for title capitalization.

If we wanted, we could import bigger rulesets, like the ones from [Red Hat](https://redhat-documentation.github.io/supplementary-style-guide/), [Microsoft](https://learn.microsoft.com/en-us/style-guide/welcome/) or [Google](https://developers.google.com/style/).

### CODE REVIEW

**Comment by yukiisbored** [comment]
I personally prefer if we leave the spellchecker enabled and maintain a vocabulary for Vale, I don't think it adds too much work.

However, for style guidelines, it might be worth to simply choose an existing one instead of starting from scratch. We could always modify them if needed in the future.

**Comment by asymmetric** [comment]
@yukiisbored any idea how to compare the different packages? Or how would you choose among them?

**Comment by asymmetric** [comment]
I decided to reduce the scope of the PR to only the uncontroversial bit, so it can be merged faster.

We can discuss styleguides and spellcheck in a follow-up PR.

WDYT?

**Review by infinisil — APPROVED** [review]
More automation is great!

**Pull request merged**
