### PR TITLE
Update nixos-configuration-on-vm.md to fix the stateVersion

### PR DESCRIPTION
**Pull request by joej164**
Was running through this tutorial using NixOS I downloaded and installed last week.  Figured I'd submit a PR to update the tutorial with the current version.

### CODE REVIEW

**Comment by olafklingt** [comment]
thank you for the pr. the direction is definitely correct. but maybe the admonition about the used nixos version needs to be more general, because there is also the minimal image (i have to check which variants matter). at the same time the comment should be kept short.

**Comment by joej164** [comment]
Per your comment, I improved the admonishments.  Happy to try and reduce the message again.

Ideally if I had more time I'd figure out how the version could be a build parameter of the docs and just be updated when new versions are released.

**Comment by fricklerhandwerk** [comment]
For the sake of keeping things working rather than always up-to-date or complete, I'd consider only adding things if they're tested exactly as described. Examples that need tinkering to are not good.

What would help here is pinning the installation image rather than pointing to whatever happens to be the most recent one. We could also add a note that updating the whole thing to the latest version is a welcome contribution. There will be people now and again who go through the motions and it would be easy for them to make a PR.

I wouldn't want to litter everything with notes amounting to "you may be out of luck". It's NixOS after all, it can and therefore should Just Work.

**Comment by olafklingt** [comment]
@fricklerhandwerk 
> What would help here is pinning the installation image 
We are talking here about the nixos-generate-config on the users computer we cannot pin that. At least not in a meaningful way.

**Review by olafklingt — APPROVED** [review]

**Comment by fricklerhandwerk** [comment]
Sure we can:
```console
$ nix-shell -p nixos-install-tools -I nixpkgs=channel:nixos-21.05
```

**Comment by olafklingt** [comment]
@joej164 hey your comment pointed us to reformulate the tutorial a bit to so that it is exactly reproducible. So i wrote this PR #804 . I think will make another PR to update it to 23.11 after its release. Feel free to comment here or elsewhere when you think that it can be improved, or that your suggested commend is still needed.

**Comment by joej164** [comment]
I looked it over, looks good.  Glad I was able to help / point out an area of improvement.

Last question....one thing that seemed missing was a tutorial on using NixOS..the configuration.nix file to just update the OS itself.  Everything was focused on Docker container, or using NixOS to build VM's.

Did I miss something?  Should I put in an issue to the above topic?

Anyways, thanks for reviewing the issue.

**Comment by olafklingt** [comment]
Yes you are right a nixOS configuration tutorial is not written jet. 
There are some open issues open that suggest NixOS tutorials:
https://github.com/NixOS/nix.dev/issues?q=is%3Aissue+is%3Aopen+nixos+configuration
I think what you are missing is already covered in those issues.

**Comment by joej164** [comment]
thanks for the link.  Should I just close this issue then?

**Pull request closed without merging**
