### PR TITLE
Update packaging-existing-software.md

### PR DESCRIPTION
**Pull request by olga-mcbfe**
update version of nixpkgs used to avoid multiple-hour cache build for first-time users trying to learn Nix

### CODE REVIEW

**Comment by fricklerhandwerk** [comment]
Thanks! Eventually all of these versions should be set automatically and all the examples tested to be working, but we're (by far) not there yet.

Although an old Nixpkgs release should not necessarily require you to build anything locally, all of that stuff is cached. Did you set up any custom cache configuration?

**Comment by willbush** [comment]
@fricklerhandwerk Think a Github action could update these pretty easy, but not sure how to test it easily. Guess we would need something like `mdbook test`, but for `nix`?

**Comment by fricklerhandwerk** [comment]
Updating is by far the easy part.

> not sure how to test it easily

This is a discussion we had many times, and there are multiple attempts to build a testing framework, taking it from various angles. Someone needs to make these ideas usable by adopting, finishing, or implementing the respective pieces of technology. Here are a few recent notes relating to @djacu's contribution to the module system tutorial: https://discourse.nixos.org/t/2024-05-16-documentation-team-meeting-notes-128/45537

**Comment by olga-mcbfe** [comment]
> Although an old Nixpkgs release should not necessarily require you to build anything locally, all of that stuff is cached. Did you set up any custom cache configuration?

I just installed nix and started to follow this tutorial. As far as I know I didn't have any custom cache configuration

**Pull request merged**
