### PR TITLE
move 'What’s the recommended process for building...?' from FAQs to Recipes

### PR DESCRIPTION
**Pull request by wamirez**
Initiating pull request to move:

- [What’s the recommended process for building custom packages?](https://nix.dev/recipes/faq#what-s-the-recommended-process-for-building-custom-packages) = "How to build a custom package?" – doesn't have a proper response

to `nix.dev/recipes/`.

### CODE REVIEW

**Comment by wamirez** [comment]
Parent issue: [Restructure FAQ section #657](https://github.com/NixOS/nix.dev/issues/657)

**Review by henrik-ch — COMMENTED** [review]
I only see a whitespace change here, was that the intention?

**Comment by wamirez** [comment]
> I only see a whitespace change here, was that the intention?

The intention is to rework and update every (question, answer), as well as to move them in more appropriate categories.

**Comment by infinisil** [comment]
@wamirez Please only open pull requests when you have an actual change to propose, this currently is just spam.

**Pull request closed without merging**
