### PR TITLE
simple server client test

### PR DESCRIPTION
**Pull request by olafklingt**
proposal to replace the complicated server client test with a simple test.
... unfortunately its so simple that one doesn't have to deal with network issues at all.

### CODE REVIEW

**Comment by fricklerhandwerk** [comment]
This is a very good idea. A tutorial should focus on the principle. But before we remove the example altogether, let's either move it to the manual where all examples are collected, or link to more third-party sources, so it's more likely for learners to find something that best matches their use case.

**Comment by olafklingt** [comment]
> But before we remove the example altogether, let's either move it to the manual where all examples are collected, or link to more third-party sources, 

Is the Manual the right place for such recipes?
I put two examples that i wrote before on the wiki:
https://nixos.wiki/wiki/NixOS_Testing_library

**Comment by fricklerhandwerk** [comment]
> Is the Manual the right place for such recipes?

I'd say it depends how you frame it. If it's a pure example, it should be in the manuals. Having a small collection there would be good.

A recipe would summarize the pattern and link to specific reference documentation for details, so it doesn't really need fully working examples.

Given the introduction in the tutorial already shows the pattern, we may leave it at that for now and consider reproducing it in isolation in the recipes section for better discoverability later.

**Comment by olafklingt** [comment]
Ok I moved the example derived from @Gabriella439 's blog to the wiki.

**Comment by fricklerhandwerk** [comment]
@olafklingt Thank you very much for the thorough research! Although the diff got quite large, in essence it's just polish. Each small change is documented (and hopefully well-enough explained) in the commit log.

This is really a great piece of exposition to an extremely powerful feature. Once we get #701 in, it will also have its due place in the learning journey. I'd like to merge it as it is now, but a brief last check from the @NixOS/documentation-team won't hurt.

**Review by fricklerhandwerk — APPROVED** [review]

**Pull request merged**
