### PR TITLE
implement the vision

### PR DESCRIPTION
**Pull request by proofconstruction**
This PR implements the grand vision [here](https://github.com/NixOS/nix.dev/blob/master/CONTRIBUTING.md#vision)

Just moved some stuff around

Done with :heart: in the Docs Team Meeting with @fricklerhandwerk @alejandrosame

### CODE REVIEW

**Comment by proofconstruction** [comment]
Fixed the redirects (I think); would really love to have #553 right about now

**Comment by proofconstruction** [comment]
Rebased over master.

**Comment by infinisil** [comment]
> Fixed the redirects (I think); would really love to have #553 right about now

Shouldn't it work if you make a PR from a main repo branch and not a fork?

**Comment by proofconstruction** [comment]
> Shouldn't it work if you make a PR from a main repo branch and not a fork?

Ah, maybe so! I don't use main repo branches. (If it does already work, we should close PR#479 and Issue#553)

**Comment by fricklerhandwerk** [comment]
I suppose for everyone's sanity's sake we should break this change down and merge it piecemeal. Otherwise we will likely break things in unpleasant ways.

**Comment by zmitchell** [comment]
This PR makes several decisions that I think each warrant their own discussions and PRs. Unless you want to endlessly rebase while we debate I suggest you follow @fricklerhandwerk's suggestion and make several smaller PRs.

**Comment by fricklerhandwerk** [comment]
I tried to compile all the insights we gleaned from this experiment in https://github.com/NixOS/nix.dev/issues/572. Closing this as a signal that it's now the time to write more tutorials.

**Pull request closed without merging**
