### PR TITLE
Add robots.txt

### PR DESCRIPTION
**Pull request by yukiisbored**
- Blocks source file and static files from web crawlers
- Defines sitemap

Closes https://github.com/NixOS/nix.dev/issues/381

### CODE REVIEW

**Review by fricklerhandwerk — APPROVED** [review]
Great!

Please split up reformatting into a separate commit.

**Comment by yukiisbored** [comment]
@fricklerhandwerk I don't get what you mean by "reformatting". If you're referring to the massive diff to poetry.lock, that's the lock file used by the Poetry package manager to lock exact versions of dependencies.

**Comment by fricklerhandwerk** [comment]
Yes, it did reformat its own lock file. Maybe make an intermediate commit that says "update poetry.lock".

**Comment by fricklerhandwerk** [comment]
Just rebase, I'll merge it. Sorry, too much stuff piled up in the meantime.

**Comment by yukiisbored** [comment]
@gilice Feel free to pick this up. I'll close it once you make your PR.

**Pull request closed without merging**
