### PR TITLE
Deploying NixOS using Terraform grammar check

### PR DESCRIPTION
**Pull request by worktheclock**

### CODE REVIEW

**Comment by worktheclock** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by sixhobbits** [comment]
@domenkozar - not sure why this one is breaking -- anything we can do to fix it?

**Comment by domenkozar** [comment]
I'll take a look, thanks!

**Review by infinisil — APPROVED** [review]
Updated this myself, looking good!

**Pull request merged**
