### PR TITLE
Add myself to Learning Journey WG

### PR DESCRIPTION
**Pull request by asymmetric**
As mentioned on Matrix, I might not have time to participate in the meetings at the proposed time.

Let me know if this still makes sense.

### CODE REVIEW

**Comment by fricklerhandwerk** [comment]
@zmitchell your document, please approve

**Review by zmitchell — APPROVED** [review]

**Comment by asymmetric** [comment]
For the record, I haven’t signed the CLA — as discussed on Matrix, we will remove it.

@zmitchell @fricklerhandwerk does that match your understanding?

**Comment by fricklerhandwerk** [comment]
I understand it's at least very likely. @asymmetric do we have an issue to track that?

**Comment by asymmetric** [comment]
@fricklerhandwerk we do now: https://github.com/NixOS/nix.dev/issues/478

**Pull request merged**
